project_id = "lmkpmnndrygjatnipfgd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.image_transformation]
enabled = true

[auth]
enabled = true
site_url = "https://ayra.app"
additional_redirect_urls = [
  "http://127.0.0.1:3001", 
  "http://localhost:3001", 
  "http://127.0.0.1:3000", 
  "http://localhost:3000", 
  "http://127.0.0.1:8080", 
  "http://localhost:8080",
  "https://ayra-unified-suite.lovable.app",
  "https://5eb95c88-7b91-431d-abcd-024a8536e78a.lovable.app",
  "https://id-preview--5eb95c88-7b91-431d-abcd-024a8536e78a.lovable.app"
]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false

[auth.sms.test_otp]
"+10000000000" = "123456"

[functions.gmail-auth]
verify_jwt = false

[functions.gmail-api]
verify_jwt = true

[functions.gmail-api-simple]
verify_jwt = false

[functions.save-attachment]
verify_jwt = true

[functions.generate-thumbnail]
verify_jwt = false

[functions.assistant]
verify_jwt = true

[functions.extract-email-contacts]
verify_jwt = true

[functions.create-stripe-onboarding]
verify_jwt = false

# Removed edge-runtime block to satisfy CLI schema